platform :ios, '8.1'

xcodeproj 'MyTabBarApp'

target :MyTabBarApp, :exclusive => true do
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
end